import{S as l,i as c}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u="44100586-6dae9d5f9d68e136096a0f58f",f="https://pixabay.com/api/";function d(s){const r=`${f}?key=${u}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(r).then(o=>o.json())}function p(s){const r=document.querySelector(".gallery"),o=s.map(e=>`
      <a class="gallery-item" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${e.likes}</p>
          <p class="info-item"><span>Views:</span> ${e.views}</p>
          <p class="info-item"><span>Comments:</span> ${e.comments}</p>
          <p class="info-item"><span>Downloads:</span> ${e.downloads}</p>
        </div>
      </a>`).join("");r.innerHTML=o,new l(".gallery a",{navText:["&#5176;","&#5171;"],captionsData:"alt",captionDelay:250}).refresh()}function m(){const s=document.querySelector(".gallery");s.innerHTML=""}const y=document.querySelector(".search-form"),h=document.querySelector(".search-input");document.querySelector(".gallery");const n=document.querySelector(".loader");y.addEventListener("submit",g);function g(s){s.preventDefault();const r=h.value.trim();if(r===""){c.error({title:"Error",message:"Please enter a search query"});return}m(),L(),d(r).then(o=>{o.hits.length===0?c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again."}):p(o.hits)}).catch(o=>{c.error({position:"topRight",message:"Error"})}).finally(()=>{v()})}function L(){n.classList.remove("hidden"),n.classList.add("visible")}function v(){n.classList.remove("visible"),n.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
